<a href="https://colab.research.google.com/github/bladerunner020/Week3/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [8]:
import torch

# Create a scalar tensor with value 42
scalar_tensor = torch.tensor(42)

print("Value:", scalar_tensor.item())

print("Number of dimensions (ndim):", scalar_tensor.ndim)

print("Shape:", scalar_tensor.shape)


Value: 42
Number of dimensions (ndim): 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [9]:
import torch

# Create a vector tensor
vector_tensor = torch.tensor([1, 2, 3, 4])

print("Value:", vector_tensor)

print("Number of dimensions (ndim):", vector_tensor.ndim)

print("Shape:", vector_tensor.shape)


Value: tensor([1, 2, 3, 4])
Number of dimensions (ndim): 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [10]:
import torch

# Create a 2x3 matrix tensor
matrix_tensor = torch.tensor([[1, 2, 3],
                              [4, 5, 6]])

print("Value:\n", matrix_tensor)

print("Number of dimensions (ndim):", matrix_tensor.ndim)

print("Shape:", matrix_tensor.shape)


Value:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions (ndim): 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [11]:
import torch

# Create sequential values from 1 to 8
tensor_3d = torch.arange(1, 9).reshape(2, 2, 2)

print("Value:\n", tensor_3d)

print("Number of dimensions (ndim):", tensor_3d.ndim)

print("Shape:", tensor_3d.shape)


Value:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions (ndim): 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [12]:
import torch

# Create a random 4x4 tensor
random_tensor = torch.rand(4, 4)

print("Random Tensor:\n", random_tensor)

print("Data type (dtype):", random_tensor.dtype)


Random Tensor:
 tensor([[0.8352, 0.6360, 0.9041, 0.1169],
        [0.3519, 0.9674, 0.2581, 0.4577],
        [0.8982, 0.6153, 0.7176, 0.6399],
        [0.6014, 0.3777, 0.4084, 0.3787]])
Data type (dtype): torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [13]:
import torch

# Create a random image tensor (channels, height, width)
image_tensor = torch.rand(3, 224, 224)

print("Image Tensor Shape:", image_tensor.shape)
print("Number of dimensions (ndim):", image_tensor.ndim)
print("Data type (dtype):", image_tensor.dtype)


Image Tensor Shape: torch.Size([3, 224, 224])
Number of dimensions (ndim): 3
Data type (dtype): torch.float32


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [14]:
import torch

# Create a 5x5 tensor filled with zeros
zeros_tensor = torch.zeros(5, 5)

print("Zeros Tensor:\n", zeros_tensor)

print("Shape:", zeros_tensor.shape)
print("Number of dimensions (ndim):", zeros_tensor.ndim)
print("Data type (dtype):", zeros_tensor.dtype)


Zeros Tensor:
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Shape: torch.Size([5, 5])
Number of dimensions (ndim): 2
Data type (dtype): torch.float32


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [15]:
import torch

# Create a random 3x3 tensor
random_tensor = torch.rand(3, 3)

# Create a tensor of ones with the same shape and dtype
ones_tensor = torch.ones_like(random_tensor)

print("Random Tensor:\n", random_tensor)
print("\nOnes Tensor (same shape):\n", ones_tensor)

print("\nRandom Tensor Shape:", random_tensor.shape)
print("Ones Tensor Shape:", ones_tensor.shape)
print("Data type:", ones_tensor.dtype)


Random Tensor:
 tensor([[0.8569, 0.8785, 0.3196],
        [0.2893, 0.9478, 0.1555],
        [0.3057, 0.6112, 0.7379]])

Ones Tensor (same shape):
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Random Tensor Shape: torch.Size([3, 3])
Ones Tensor Shape: torch.Size([3, 3])
Data type: torch.float32


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [16]:
import torch

# Create tensor from 0 to 20 with step of 2
even_tensor = torch.arange(0, 21, 2)

print("Tensor:", even_tensor)

print("Shape:", even_tensor.shape)
print("Number of dimensions (ndim):", even_tensor.ndim)
print("Data type (dtype):", even_tensor.dtype)


Tensor: tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
Shape: torch.Size([11])
Number of dimensions (ndim): 1
Data type (dtype): torch.int64


## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [17]:
import torch

# Create tensor with float16 dtype
tensor_float16 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# Create tensor with int64 dtype
tensor_int64 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.int64)

print("Float16 Tensor:", tensor_float16)
print("Float16 dtype:", tensor_float16.dtype)

print("\nInt64 Tensor:", tensor_int64)
print("Int64 dtype:", tensor_int64.dtype)


Float16 Tensor: tensor([1., 2., 3.], dtype=torch.float16)
Float16 dtype: torch.float16

Int64 Tensor: tensor([1, 2, 3])
Int64 dtype: torch.int64


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [18]:
import torch

# Original float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# Convert to float32
float32_tensor = float16_tensor.to(torch.float32)
# Alternatively: float32_tensor = float16_tensor.type(torch.float32)

print("Original Tensor (float16):", float16_tensor, "dtype:", float16_tensor.dtype)
print("Converted Tensor (float32):", float32_tensor, "dtype:", float32_tensor.dtype)


Original Tensor (float16): tensor([1., 2., 3.], dtype=torch.float16) dtype: torch.float16
Converted Tensor (float32): tensor([1., 2., 3.]) dtype: torch.float32


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [19]:
import torch

# Create a random tensor of shape (2, 3, 4)
random_tensor = torch.rand(2, 3, 4)

print("Random Tensor:\n", random_tensor)
print("Shape:", random_tensor.shape)
print("Data type (dtype):", random_tensor.dtype)
print("Device:", random_tensor.device)


Random Tensor:
 tensor([[[0.4835, 0.2275, 0.3400, 0.9178],
         [0.6561, 0.9373, 0.4689, 0.8964],
         [0.6766, 0.8040, 0.0178, 0.7343]],

        [[0.2718, 0.1107, 0.2147, 0.4534],
         [0.9843, 0.5742, 0.2074, 0.8396],
         [0.2784, 0.7920, 0.4181, 0.2738]]])
Shape: torch.Size([2, 3, 4])
Data type (dtype): torch.float32
Device: cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [20]:
import torch

# Create tensor
tensor = torch.tensor([10, 20, 30], dtype=torch.float32)  # use float for division

# Add 5
tensor = tensor + 5
print("After adding 5:", tensor)

# Subtract 10
tensor = tensor - 10
print("After subtracting 10:", tensor)

# Multiply by 2
tensor = tensor * 2
print("After multiplying by 2:", tensor)

# Divide by 10
tensor = tensor / 10
print("After dividing by 10:", tensor)


After adding 5: tensor([15., 25., 35.])
After subtracting 10: tensor([ 5., 15., 25.])
After multiplying by 2: tensor([10., 30., 50.])
After dividing by 10: tensor([1., 3., 5.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [21]:
import torch

# Create random tensors
A = torch.rand(2, 3)
B = torch.rand(3, 2)

# Perform matrix multiplication
C = torch.matmul(A, B)  # or A @ B

print("Tensor A (2x3):\n", A)
print("\nTensor B (3x2):\n", B)
print("\nMatrix Multiplication Result (2x2):\n", C)
print("Shape of result:", C.shape)


Tensor A (2x3):
 tensor([[0.2175, 0.1010, 0.7170],
        [0.5326, 0.3202, 0.7426]])

Tensor B (3x2):
 tensor([[0.2058, 0.8382],
        [0.8045, 0.0336],
        [0.2593, 0.3379]])

Matrix Multiplication Result (2x2):
 tensor([[0.3120, 0.4280],
        [0.5598, 0.7081]])
Shape of result: torch.Size([2, 2])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [22]:
import torch

# Create tensor with values from 0 to 100
tensor = torch.arange(0, 101, dtype=torch.float32)  # float for mean

# Compute statistics
min_val = tensor.min()
max_val = tensor.max()
mean_val = tensor.mean()
sum_val = tensor.sum()

print("Tensor:", tensor)
print("Min:", min_val.item())
print("Max:", max_val.item())
print("Mean:", mean_val.item())
print("Sum:", sum_val.item())


Tensor: tensor([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,
         24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,
         36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
         48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,
         60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,
         72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,
         84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,
         96.,  97.,  98.,  99., 100.])
Min: 0.0
Max: 100.0
Mean: 50.0
Sum: 5050.0


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [23]:
import torch

# Tensor from 0 to 100
tensor = torch.arange(0, 101)

# Find indices of min and max
min_index = torch.argmin(tensor)
max_index = torch.argmax(tensor)

print("Tensor:", tensor)
print("Index of minimum value:", min_index.item())
print("Index of maximum value:", max_index.item())


Tensor: tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100])
Index of minimum value: 0
Index of maximum value: 100


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [24]:
import torch

# Create a tensor with values from 0 to 9
tensor_1d = torch.arange(10)

# Reshape to (2, 5)
tensor_2d = tensor_1d.reshape(2, 5)

print("Original Tensor (1D):", tensor_1d)
print("Shape:", tensor_1d.shape)

print("\nReshaped Tensor (2x5):\n", tensor_2d)
print("Shape:", tensor_2d.shape)


Original Tensor (1D): tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Shape: torch.Size([10])

Reshaped Tensor (2x5):
 tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
Shape: torch.Size([2, 5])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [25]:
import torch

# Create two tensors
tensor1 = torch.tensor([[1, 2],
                        [3, 4]])
tensor2 = torch.tensor([[5, 6],
                        [7, 8]])

# Vertical stacking (along rows) → torch.vstack or torch.cat(dim=0)
vertical_stack = torch.vstack((tensor1, tensor2))
# Horizontal stacking (along columns) → torch.hstack or torch.cat(dim=1)
horizontal_stack = torch.hstack((tensor1, tensor2))

print("Tensor 1:\n", tensor1)
print("Tensor 2:\n", tensor2)
print("\nVertical Stack (4x2):\n", vertical_stack)
print("Shape:", vertical_stack.shape)

print("\nHorizontal Stack (2x4):\n", horizontal_stack)
print("Shape:", horizontal_stack.shape)


Tensor 1:
 tensor([[1, 2],
        [3, 4]])
Tensor 2:
 tensor([[5, 6],
        [7, 8]])

Vertical Stack (4x2):
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Shape: torch.Size([4, 2])

Horizontal Stack (2x4):
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
Shape: torch.Size([2, 4])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [26]:
import torch

# Create tensor of shape (1, 3, 1)
tensor = torch.tensor([[[10], [20], [30]]])
print("Original Tensor:\n", tensor)
print("Shape:", tensor.shape)

# Squeeze tensor → removes dimensions of size 1
squeezed_tensor = tensor.squeeze()
print("\nSqueezed Tensor:\n", squeezed_tensor)
print("Shape:", squeezed_tensor.shape)

# Unsqueeze tensor on dim=0 → adds a dimension at position 0
unsqueezed_tensor = squeezed_tensor.unsqueeze(0)
print("\nUnsqueezed Tensor (dim=0):\n", unsqueezed_tensor)
print("Shape:", unsqueezed_tensor.shape)


Original Tensor:
 tensor([[[10],
         [20],
         [30]]])
Shape: torch.Size([1, 3, 1])

Squeezed Tensor:
 tensor([10, 20, 30])
Shape: torch.Size([3])

Unsqueezed Tensor (dim=0):
 tensor([[10, 20, 30]])
Shape: torch.Size([1, 3])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [27]:
import torch

# Create a random image tensor (C, H, W)
image_tensor = torch.rand(3, 100, 100)
print("Original Shape (C, H, W):", image_tensor.shape)

# Permute to (H, W, C)
image_permuted = image_tensor.permute(1, 2, 0)
print("Permuted Shape (H, W, C):", image_permuted.shape)


Original Shape (C, H, W): torch.Size([3, 100, 100])
Permuted Shape (H, W, C): torch.Size([100, 100, 3])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [28]:
import torch

# Create the tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

print("Original Tensor:\n", tensor)
print("Shape:", tensor.shape)

# Index to get 5
value_5 = tensor[0, 1, 1]  # batch 0, second row (index 1), second column (index 1)
print("\nValue 5:", value_5.item())

# Index to get the entire second row
second_row = tensor[0, 1, :]  # batch 0, second row, all columns
print("Second Row:", second_row)


Original Tensor:
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape: torch.Size([1, 3, 3])

Value 5: 5
Second Row: tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [29]:
import numpy as np
import torch

# Create a NumPy array
np_array = np.array([1, 2, 3, 4])
print("NumPy Array:", np_array)
print("Shape:", np_array.shape)
print("Dtype:", np_array.dtype)

# Convert NumPy array to PyTorch tensor
torch_tensor = torch.from_numpy(np_array)
print("\nPyTorch Tensor:", torch_tensor)
print("Shape:", torch_tensor.shape)
print("Dtype:", torch_tensor.dtype)


NumPy Array: [1 2 3 4]
Shape: (4,)
Dtype: int64

PyTorch Tensor: tensor([1, 2, 3, 4])
Shape: torch.Size([4])
Dtype: torch.int64


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [30]:
import torch

# Create a PyTorch tensor
tensor = torch.tensor([5, 6, 7, 8])
print("PyTorch Tensor:", tensor)
print("Shape:", tensor.shape)
print("Dtype:", tensor.dtype)

# Convert to NumPy array
np_array = tensor.numpy()
print("\nNumPy Array:", np_array)
print("Shape:", np_array.shape)
print("Dtype:", np_array.dtype)


PyTorch Tensor: tensor([5, 6, 7, 8])
Shape: torch.Size([4])
Dtype: torch.int64

NumPy Array: [5 6 7 8]
Shape: (4,)
Dtype: int64


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [31]:
import torch

torch.manual_seed(77)

# Create the first random tensor
tensor1 = torch.rand(2, 2)

# Reset the seed to 77 again before creating the second tensor
torch.manual_seed(77)
tensor2 = torch.rand(2, 2)

print("Tensor 1:\n", tensor1)
print("\nTensor 2:\n", tensor2)

# Check if they are equal
are_equal = torch.equal(tensor1, tensor2)
print("\nAre the tensors equal?", are_equal)


Tensor 1:
 tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])

Tensor 2:
 tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])

Are the tensors equal? True


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [32]:
import torch

# Check if CUDA is available
if torch.cuda.is_available():
    device = torch.device("cuda")  # GPU
    print("CUDA is available. Using GPU.")
else:
    device = torch.device("cpu")   # CPU
    print("CUDA is not available. Using CPU.")

tensor = torch.rand(3, 3, device=device)
print("Tensor Device:", tensor.device)


CUDA is not available. Using CPU.
Tensor Device: cpu


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [33]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Create a tensor on CPU
tensor = torch.tensor([1.0, 2.0, 3.0, 4.0])
print("\nOriginal Tensor:", tensor, "Device:", tensor.device)

# Move tensor to GPU (if available)
tensor_gpu = tensor.to(device)
print("Tensor on GPU (if available):", tensor_gpu, "Device:", tensor_gpu.device)

# Move tensor back to CPU
tensor_cpu = tensor_gpu.to("cpu")
print("Tensor back on CPU:", tensor_cpu, "Device:", tensor_cpu.device)

# Convert to NumPy array
np_array = tensor_cpu.numpy()
print("NumPy Array:", np_array, "Type:", type(np_array))


Using device: cpu

Original Tensor: tensor([1., 2., 3., 4.]) Device: cpu
Tensor on GPU (if available): tensor([1., 2., 3., 4.]) Device: cpu
Tensor back on CPU: tensor([1., 2., 3., 4.]) Device: cpu
NumPy Array: [1. 2. 3. 4.] Type: <class 'numpy.ndarray'>
